config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

HearkenFinal::Application.routes.draw do
  constraints(AuthConstraint.new) do
    resources :cats
    resources :users
    resources :votes, only: [:index, :new, :create, :destroy]
  end

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  resources :votes, only: [:create]
  
  root to: "home#index"

  get "*any", to: redirect('/404')
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  # validations
  validates :url, presence: true
  validates :description, presence: true

  # associations
  belongs_to :user
  has_many :votes, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # validations
  validates :username, presence: true
  validates :password, presence: true
  validates :password_confirmation, presence: true

  has_secure_password

  # associations
  has_many :cats
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  # validations
  validates :option, presence: true
  validates :ip_address, presence: true

  # associations
  belongs_to :cat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  require 'csv'

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  def index
    @cats = Cat.all
  end

  def show
  end

  def new
    @cat = Cat.new
  end

  def edit
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user = current_user
    if @cat.save
      redirect_to @cat
    else
      render action: 'new'
    end
  end

  def update
    if @cat.update_attributes(cat_params)
      redirect_to @cat
    else
      render action: 'edit'
    end
  end

  def destroy
    @cat.destroy
    redirect_to cats_url
  end

  private

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:url, :description, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cats = Cat.limit(2).order("RANDOM()")
    @ip   = request.remote_ip
    @vote = Vote.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to :root
    else
      @error = "Incorrect username or password"

      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @cats = @user.cats
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render action: 'new'
    end
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render action: 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private

  def set_user
    @user = User.find(params[:id])
  end  

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :destroy]

  def index
    @votes = Vote.all
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"cat-votes.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def new
    @vote = Vote.new
    redirect_to '/404'
  end

  def create
    @vote = Vote.new(vote_params)
    @vote.save
    redirect_to root_url
  end

  def destroy
    @vote.destroy
    redirect_to votes_url
  end

  private
  
  def set_vote
    @vote = Vote.find(params[:id])
  end

  def vote_params
    params.require(:vote).permit(:option, :ip_address, :cat_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_form.html.erb
  <% if @cat.errors.any? %>
    <div class="bgError">
      <% @cat.errors.full_messages.each do |msg| %>
        *<%= msg %><br>
      <% end %>
    </div>
  <% end %>
<%= form_for(@cat) do |f| %>
  <div class="actions">
    <table class="new-edit">
      <tbody>
        <tr><td></td><td><%= link_to '<i class="fa fa-ban"></i>'.html_safe, @cat %> <%= link_to '<i class="fa fa-list"></i>'.html_safe, cats_path %><% if !current_page? new_cat_path %> <%= link_to '<i class="fa fa-trash"></i>'.html_safe, @cat, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td></tr>
        <tr><td>URL</td><td><%= text_field :cat, :url %></td></tr>
        <tr><td valign="top"><p>Description</p></td><td><%= text_area :cat, :description, maxlength: 40 %></td></tr>
        <tr><td></td><td><div id="charNum"><span>40</span> characters left</div><%= f.submit %>&nbsp;&nbsp;<%= link_to 'Cancel', @cat %></td></tr>
      </tbody>
    </table>
  </div>
<% end %>

<% content_for :jsforms do %>
<script>
  $(document).ready(function(){

    function charRemainInit() {
      var descLength = $('#cat_description').val().length;
      $('#charNum span').text(40-descLength);
    }

    function updateWhileTyping() {
      $('textarea').keyup(function () {
          var charRemain = 40 - $(this).val().length;
          if (charRemain < 0) {
              charRemain = 0;
          }
          $('#charNum span').text(charRemain);
      });       
    }

    charRemainInit();
    updateWhileTyping();

  });
</script>
<% end %>

app/views/cats/edit.html.erb
<h1>Edit Cat #<%= @cat.id %></h1>

<div id="formContainer">
<%= render 'form' %>

</div>

app/views/cats/index.html.erb
<h1 class="model-index">Cats Meow <%= link_to '<i class="fa fa-plus-circle"></i>'.html_safe, new_cat_path %></h1>

<div id="container">

  <script type='text/template' id="cat-template">
  <%% _.each(cats, function(cat) { %>  
    <tr> 
      <td><div class="imgDiv"><a href="/cats/<%%= cat.id %>"><img src="<%%= cat.url %>" /></a></div></td>
      <td class="desc"><a href="/cats/<%%= cat.id %>"><%%= cat.description %></a><a href="/cats/<%%= cat.id %>/edit"><i class="fa fa-pencil"></i> <a data-confirm="Are you sure?" data-method="delete" href="/cats/<%%= cat.id %>" rel="nofollow"><i class="fa fa-trash"></i></a></td>
      <td><span><%%= cat.zomg %></span></td>
      <td><span><%%= cat.amazing %></span></td>
    </tr>
  <%% }); %>
  </script>

  <table class="allCats">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th><a href="#" onclick="sortVotes(0, 'zomg');">ZOMG! Cute!</a></th>
        <th><a href="#" onclick="sortVotes(1, 'amazing');">Amazing! So Beautiful!</a></th>
      </tr>
    </thead>

    <tbody></tbody>
  </table>

  <script>

    var cats = [];
    <% @cats.each do |cat| %>
      cats.push({id: '<%= cat.id %>', url: '<%= cat.url %>', description: '<%= cat.description %>', zomg: '<%= cat.votes.where(option: 0).count %>', amazing: '<%= cat.votes.where(option: 1).count %>'});
    <% end %>
    var sortStatus = [false,false];

    function displayCats(){
      var cat_view = $("#cat-template").html();
      $('table tbody').html('');
      $('table tbody').append(_.template(cat_view, {cats:cats}));
    }

    function dataSort(index, key){
      cats = _.sortBy(cats, key);
      if (sortStatus[index] == false){
        cats = cats.reverse();
      }
    }

    function sortVotes(arrayIndex, key){
      dataSort(arrayIndex, key);
      sortStatus[arrayIndex] = !sortStatus[arrayIndex];
      displayCats();
    }

    displayCats();

  </script>
  
</div>

app/views/cats/new.html.erb
<h1>Add Cat</h1>

<div id="formContainer">
<%= render 'form' %>

</div>

app/views/cats/show.html.erb
<h1>Cat #<%= @cat.id %></h1>
<!--p id="notice"><%= notice %></p-->

<div id="container">
  <table class="show">
    <tbody>
      <tr>
        <td></td>
        <td><%= link_to '<i class="fa fa-list"></i>'.html_safe, cats_path %> <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_cat_path %> <%= link_to '<i class="fa fa-trash"></i>'.html_safe, @cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr>
        <td><img src="<%= @cat.url %>" class="showCatImg" /><p><%= @cat.description %></p></td>
        <td>
          <p><strong>Votes</strong><br>
            "ZOMG! Cute!" - <strong><%= @cat.votes.where(option: 0).count %></strong><br>
            "Amazing! So Beautiful!" - <strong><%= @cat.votes.where(option: 1).count %></strong>
          </p>
          <p><strong>URL</strong><br><%= @cat.url.truncate(44) %></p>
          <p><strong>Contributor</strong><br><%= @cat.user.username %></p>
          <p><strong>Date Added</strong><br><%= @cat.created_at.strftime("%B %-d, %Y") %></p>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<h1 class="index">ZOMG! CAT HEALTH!</h1>

<div id="container">

  <div class="catContainer">
  <% @cats.each_with_index do |cat, index| %>
    <div class="picWithBtn">
    <div class="polaroid">
    <div class="catImg"><img src="<%= cat.url %>" /></div>
    <p><%= cat.description %></p>
    </div>
    <%= form_for(@vote) do |f| %>
      <%= f.hidden_field :option, value: index %>
      <%= f.hidden_field :ip_address, value: @ip %>
      <%= f.hidden_field :cat_id, value: cat.id %>
        <% if index == 0 %>
          <% btnLabel = 'ZOMG! Cute!' %>
        <% else %>
          <% btnLabel = 'Amazing! So Beautiful!' %>
        <% end %>
      <%= f.submit btnLabel %>
    <% end %>
    </div>
  <% end %>
    <div class="clear"></div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZOMG! CAT HEALTH!</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Slackey' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= yield :jsforms %>
  <%= csrf_meta_tags %> 
</head>
<body>
  <div id="submenu">
<% if current_user %>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Cats Meow', cats_path %></li>
      <li><%= link_to 'Votes', votes_path %></li>
      <li><%= link_to 'Admin Users', users_path %></li>
    </ul>
    <div class="username">
      <p>Welcome, <%= link_to current_user.username, current_user %> | <%= link_to "Logout", logout_path, :method => "delete" %></p>
    </div>
<% elsif !current_page?('/login') %>
    <div class="username">
      <p><%= link_to "Login", login_path %></p>
    </div>
<% elsif current_page?('/login') %>
    <div class="username">
      <p><%= link_to "Home", root_path %></p>
    </div>
<% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
  <% if @user.errors.any? %>
    <div class="bgError">
      <% @user.errors.full_messages.each do |msg| %>
        *<%= msg %><br>
      <% end %>
    </div>
  <% end %>
<%= form_for(@user) do |f| %>
  <div class="actions">
    <table class="new-edit">
      <tbody>
        <tr><td></td><td><%= link_to '<i class="fa fa-ban"></i>'.html_safe, @user %> <%= link_to '<i class="fa fa-list"></i>'.html_safe, users_path %><% if !current_page? new_user_path %> <%= link_to '<i class="fa fa-trash"></i>'.html_safe, @user, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td></tr>
        <tr><td>Username</td><td><%= f.text_field :username %></td></tr>
        <tr><td>Password</td><td><%= f.password_field :password %></td></tr>
        <tr><td>Confirm Password</td><td><%= f.password_field :password_confirmation %></td></tr>
        <% if current_page? new_user_path %><% userVar = 'Create Admin' %><% else %><% userVar = 'Edit Admin' %><% end %>
        <tr><td></td><td><%= f.submit userVar %>&nbsp;&nbsp;<%= link_to 'Cancel', @user %></td></tr>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit @<%= @user.username %></h1>

<div id="formContainer">
<%= render 'form' %>

</div>

app/views/users/index.html.erb
<h1 class="model-index">Admins <%= link_to '<i class="fa fa-plus-circle"></i>'.html_safe, new_user_path %></h1>

<div id="container">

  <table>
    <thead>
      <tr>
        <th>username</th>
        <th>#cats</th>
        <th>last cat added</th>
        <th>admin since</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.username, user %> <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_user_path(user) %> <%= link_to '<i class="fa fa-trash"></i>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= user.cats.count %></td>
          <td><% if user.cats.count > 0 %><%= user.cats.order("created_at").last.created_at.strftime("%B %-d, %Y at %-l:%M%p") %><% else %>No Cats Yet<% end %></td>
          <td><%= user.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/new.html.erb
<h1>Add Admin</h1>

<div id="formContainer">
<%= render 'form' %>

</div>

app/views/users/show.html.erb
<h1>@<%= @user.username %></h1>
<!-- <p id="notice"><%= notice %></p> -->

<div id="container">
  <table class="show">
    <tbody>
      <tr>
        <td></td>
        <td><%= link_to '<i class="fa fa-list"></i>'.html_safe, users_path %> <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_user_path %> <%= link_to '<i class="fa fa-trash"></i>'.html_safe, @user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr>
        <td><strong>Admin Since</strong></td>
        <td><p><%= @user.created_at.strftime("%B %-d, %Y") %></p></td>
      </tr>
      <tr>
        <td><strong>Cat Photos (<%= @cats.count %>)</strong></td>
        <td><% @cats.each do |cat| %>
          <a href="/cats/<%= cat.id %>"><div class="imgDiv"><img src="<%= cat.url %>" /></div></a>
        <% end %></td>
      </tr>
      <tr>
        <td><strong>Last Image Added</strong></td>
        <td><p><% if @cats.count != 0 %><%= @cats.order("created_at").last.created_at.strftime("%B %-d, %Y at %-l:%M%p") %><% else %>No Cats Yet<% end %></p></td>
      </tr>
    <tbody>
  </table>
</div>

app/views/votes/index.csv.erb
<%- headers = [nil, 'cat url', 'ip address of voter', 'vote'] -%>
<%= CSV.generate_line headers %>
<%- @votes.each_with_index do |vote,index| -%>
  <%- if vote.option == 0 ? label = "ZOMG! Cute!" : label = "Amazing! So Beautiful!" -%><%- end -%>
  <%= CSV.generate_line([index+1, vote.cat.url, vote.ip_address, label]) %>
<%- end -%>

app/views/votes/index.html.erb
<h1 class="model-index">All Votes (<%= @votes.count %>)</h1>

<div id="container">

  <table>
    <thead>
      <tr>
        <th></th>
        <th>Date</th>
        <th>IP Address</th>
        <th>Cat ID</th>      
        <th>Option</th>
        <th><%= link_to '<i class="fa fa-download"></i>'.html_safe, votes_path(format: :csv) %></th>
      </tr>
    </thead>

    <tbody>
      <% @votes.each_with_index do |vote, index| %>
        <tr>
          <td><%= index + 1 %>)</td>
          <td><%= vote.created_at.strftime("%B %-d, %Y") %></td>
          <td><%= vote.ip_address %></td>
          <td><%= vote.cat_id %></td>
          <td><% if vote.option == 0 %>ZOMG! Cute!<% else %>Amazing! So Beautiful!<% end %></td>
          <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>